// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {CSSDesignToken} from '@microsoft/fast-foundation';
import {
	badgeBackground,
	badgeForeground,
	buttonBorder,
	buttonPrimaryBackground,
	buttonPrimaryForeground,
	buttonPrimaryHoverBackground,
	buttonSecondaryBackground,
	buttonSecondaryForeground,
	buttonSecondaryHoverBackground,
	checkboxBackground,
	checkboxBorder,
	checkboxForeground,
	contrastActiveBorder,
	contrastBorder,
	dividerBackground,
	dropdownBackground,
	dropdownBorder,
	dropdownForeground,
	focusBorder,
	fontFamily,
	fontWeight,
	foreground,
	inputBackground,
	inputForeground,
	inputPlaceholderForeground,
	linkActiveForeground,
	linkForeground,
	listActiveSelectionBackground,
	listActiveSelectionForeground,
	listHoverBackground,
	panelTabActiveBorder,
	panelTabActiveForeground,
	panelTabForeground,
	panelViewBackground,
	panelViewBorder,
	progressBackground,
	quickInputBackground,
	typeRampBaseFontSize,
} from '../../design-tokens';

/**
 * A mapping of all the Visual Studio Code theme CSS variables mapped to the
 * toolkit design tokens.
 */
export const tokenMappings: {[index: string]: CSSDesignToken<string>} = {
	'--vscode-badge-background': badgeBackground,
	'--vscode-badge-foreground': badgeForeground,
	'--vscode-button-border': buttonBorder,
	'--vscode-button-background': buttonPrimaryBackground,
	'--vscode-button-foreground': buttonPrimaryForeground,
	'--vscode-button-hoverBackground': buttonPrimaryHoverBackground,
	'--vscode-button-secondaryBackground': buttonSecondaryBackground,
	'--vscode-button-secondaryForeground': buttonSecondaryForeground,
	'--vscode-button-secondaryHoverBackground': buttonSecondaryHoverBackground,
	'--vscode-checkbox-background': checkboxBackground,
	'--vscode-checkbox-border': checkboxBorder,
	'--vscode-checkbox-foreground': checkboxForeground,
	'--vscode-contrastActiveBorder': contrastActiveBorder,
	'--vscode-contrastBorder': contrastBorder,
	'--vscode-dropdown-background': dropdownBackground,
	'--vscode-dropdown-border': dropdownBorder,
	'--vscode-dropdown-foreground': dropdownForeground,
	'--vscode-focusBorder': focusBorder,
	'--vscode-font-family': fontFamily,
	'--vscode-font-size': typeRampBaseFontSize,
	'--vscode-font-weight': fontWeight,
	'--vscode-foreground': foreground,
	'--vscode-input-background': inputBackground,
	'--vscode-input-foreground': inputForeground,
	'--vscode-input-placeholderForeground': inputPlaceholderForeground,
	'--vscode-list-activeSelectionBackground': listActiveSelectionBackground,
	'--vscode-list-activeSelectionForeground': listActiveSelectionForeground,
	'--vscode-list-hoverBackground': listHoverBackground,
	'--vscode-panel-background': panelViewBackground,
	'--vscode-panel-border': panelViewBorder,
	'--vscode-panelTitle-activeBorder': panelTabActiveBorder,
	'--vscode-panelTitle-activeForeground': panelTabActiveForeground,
	'--vscode-panelTitle-inactiveForeground': panelTabForeground,
	'--vscode-progressBar-background': progressBackground,
	'--vscode-quickInput-background': quickInputBackground,
	'--vscode-settings-dropdownListBorder': dividerBackground,
	'--vscode-textLink-activeForeground': linkActiveForeground,
	'--vscode-textLink-foreground': linkForeground,
};
